apiVersion: v1
kind: Pod
metadata: 
  name: db-pod
  labels:
    app: db-pod
    type: front-end
spec:
  containers:
    - name: db-app-container
      image: postgres
      env:
        - name: POSTGRES_USERNAME
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"