apiVersion: v1
kind: Service
metadata:
  name: result-app-svc
spec:
  type: NodePort
  ports:
     - targetPort: 80
       port: 80
       nodePort: 30010
  selector:
   app: result-app
   type: front-end