apiVersion: v1
kind: Pod
metadata: 
    name: result-app
    labels:
      app: result-app
      type: front-end
spec:
  containers:
    - name: resultapp-container
      image: vsiraparapu/result-app
      ports:
        - containerPort: 80