apiVersion: v1
kind: Service
metadata:
  name: vote-app-svc
spec:
  type: NodePort
  ports:
     - targetPort: 80
       port: 80
       nodePort: 30009
  selector:
    app: vote-app
    type: front-end