apiVersion: v1
kind: Pod
metadata: 
    name: vote-app
    labels:
      app: vote-app
      type: front-end
spec:
  containers:
    - name: voteapp-container
      image: vsiraparapu/voting-app
      ports:
        - containerPort: 80